### ISSUE TITLE
Gluster 4.x and GD2 (GlusterD2) support

### ISSUE THREAD

**Issue by sammcj** [voxpupuli/puppet-gluster#153]
Gluster 4.x has been in pre-release for some time and ended up being release last week (14/03/2018).

It would be great to see support for Gluster 4.x in this module so people can start upgrading.

- [Announcement](https://www.gluster.org/announcing-gluster-4-0/)
- [Release Notes](https://docs.gluster.org/en/latest/release-notes/4.0.0/)
- [Quick Start Guide](https://github.com/gluster/glusterd2/blob/master/doc/quick-start-user-guide.md)
- [Upgrade Guide](https://docs.gluster.org/en/latest/Upgrade-Guide/upgrade_to_4.0/)
- [More about Gluster D2](https://www.gluster.org/more-about-gluster-d2/)

**Comment by sammcj** [comment]
FYI Gluster 4.1.0 has now been released.

**Comment by bronislav** [comment]
@sammcj Since gluster 4.0 and 4.1 already available in http://mirror.centos.org/centos/7/storage/x86_64/ you should be able to install these versions without (any?) changes in the module. Highly possible that other things could be broken.

**Comment by sammcj** [comment]
Gluster 4 onwards is a complete rewrite (in go) from the ground up.

Gluster is now mainly API driven and uses different command line tools so I’d say the module needs a rewrite / major update to support it.

I’d offer to give it a crack but I’m unfortunately really bogged down with another major project at the moment.

https://fosdem.org/2018/schedule/event/gluster4_and_gd2/attachments/slides/2419/export/events/attachments/gluster4_and_gd2/slides/2419/gluster4_fosdem2018.pdf

--
Sam McLeod

**Comment by sammcj** [comment]
FYI - just a heads up, Gluster 3.1.3 is no longer available and has been completely purged from the Gluster repos, the official word is to please use Gluster 4 (4.1 now I guess).

A side note, we've tested clients running Gluster Client 4.1 and they can connect to Gluster 3.1.3.

But be ware - Gluster 3 is dying very quickly!

**Comment by ekohl** [comment]
In https://github.com/voxpupuli/puppet-gluster/pull/170 I'm removing 3.8 repo support. Because I don't use gluster I don't have time to rewrite to Gluster 4.

**Comment by sammcj** [comment]
I've tested this module with Gluster 4 and it works, but it definitely does not work with GlusterD2 (GD2).

**Comment by af6140** [comment]
Looks like no active development going on for this module.

**Comment by bronislav** [comment]
@af6140 GlusterD2 in under active development and wasn't considered production ready when I checked it couple month ago.
