### ISSUE TITLE
Name of server service is different in Debian

### ISSUE THREAD

**Issue by zstyblik** [voxpupuli/puppet-gluster#19]
Hello,

the name of glusterfs server service is different in Debian. It's not `glusterd`, but `glusterfs-server`. I'll pitch two solutions, although I don't know what's the preferred(THE correct) way doing this in Puppet.

Service name can come from variable, therefore why not to put it there. Its value should be determined by LSB. So far so  good. Now, where to put this logic.
1. Either into `params.pp`
2. or put `case` into `service.pp`

**Comment by skpy** [comment]
There's not a lot of support for anything other than Red Hat based systems in this module.

The correct solution is to define `service_name` variable and add an `elseif` condition to [params.pp](https://github.com/covermymeds/puppet-gluster/blob/master/manifests/params.pp#L53); and then add a `service_name` parameter to [service.pp](https://github.com/covermymeds/puppet-gluster/blob/master/manifests/service.pp#L24) that pulls the name from `$::gluster::params::service_name`.

We don't use Debian or Ubuntu regularly, so this isn't a high priority change for us; but a pull request would be super helpful!  ;)

**Comment by zstyblik** [comment]
> There's not a lot of support for anything other than Red Hat based systems in this module.
> We don't use Debian or Ubuntu regularly, so this isn't a high priority change for us

I know. I've read issues and PRs and that's ok. ;)

I felt like reporting this while it's a fresh experience. Also, now I(and others) know what the preferred solution is. I'll see what can be done about PR.

**Comment by zstyblik** [comment]
As a matter of fact, this issue seems to be addressed in PR https://github.com/covermymeds/puppet-gluster/pull/7. Is there any progress/word from original author(submitter) on addressing comment issues and getting it merged? Should I take his work, update it and submit new PR? Or just take part that does it(`params.pp`)?

**Comment by skpy** [comment]
I'm happy to merge #7, but it lacks rspec tests.  Is that something you'd like to contribute?

**Comment by zstyblik** [comment]
> I'm happy to merge #7, but it lacks rspec tests. Is that something you'd like to contribute?

Let me read up on it a bit, then I'll give you my answer. It's not a problem in general way, but I know nothing abour rspec tests.

**Comment by zstyblik** [comment]
Ok, I finally caught 5 minutes to give rspec a look and it looks like a Chinese to me. However, I've found couple tutorials. I'll try to give a read those, may be it'll get better. If you have any tips or advice how to learn rspec, fire away :)

**Comment by jyaworski** [comment]
Is this still an issue?

**Comment by jacksgt** [comment]
As far as I can tell this issue is resolved:

https://github.com/voxpupuli/puppet-gluster/blob/master/manifests/params.pp#L54

Issue can be closed.

**Comment by jacksgt** [comment]
@Dan33l Looks fine to me, too. Or whom are you targeting with "you"?

>  Are you using an other OS version ?

**Comment by Dan33l** [comment]
@jacksgt ah yes, since you specified the version you are using, i expected it is clear but it is not.

@zstyblik are you using an other version of Debian OS ?

> @Dan33l Looks fine to me, too. Or whom are you targeting with "you"?
> 
> > Are you using an other OS version ?

**Comment by jacksgt** [comment]
His last comment is from August 2015. Three years ago he was probably using Debian Jessie (8).

**Comment by Dan33l** [comment]
Ah yes the PR introducing Debian was done 2 years ago. I didn't check dates.
@jacksgt thank you.

**Comment by zstyblik** [comment]
@Dan33l yes, it was, back then, brand new Debian 8 :)

**Comment by Dan33l** [comment]
Adding support of Debian 8 looks to be an other issue, since the module is already supporting Debian (9).

So please fill free to propose a PR adding Debian 8 support.
