### ISSUE TITLE
Deal with replica add-brick math

### ISSUE THREAD

**Issue by skpy** [voxpupuli/puppet-gluster#2]
The current code will fail when [adding a new replica member](https://github.com/covermymeds/puppet-gluster/blob/master/manifests/volume.pp#L184). The value to check should be the total number of replica disks, not just the quantity of new disks.

**Comment by jyaworski** [comment]
Is this still an issue?

**Comment by sammcj** [comment]
@jyaworski - currently there are a lot of open and potentially stale issues on this module, may I suggest perhaps closing off issues with no responses from people for several months etc...?

**Comment by ekohl** [comment]
Agreed. Closing due to its age.
