### ISSUE TITLE
Newer versions of Gluster 

### ISSUE THREAD

**Issue by tsmgeek** [voxpupuli/puppet-gluster#217]
Will this module work with the newer versions of Gluster >4?

**Comment by tsmgeek** [comment]
what is the status of this project? seems there are new commits to master but no releases

**Comment by kenyon** [comment]
Someone just needs to prepare a new release pull request. See https://voxpupuli.org/docs/releasing_version/ or a previous release PR for info and examples.

**Comment by tsmgeek** [comment]
closing this in favor of #224
