### ISSUE TITLE
New Module Version for Puppet Forge?

### ISSUE THREAD

**Issue by rwaffen** [voxpupuli/puppet-gluster#224]
Hi puppet-gluster Team,

can we have a new module version for puppet forge, please? :)

THX and Greeting, R

**Comment by kenyon** [comment]
Someone just needs to prepare a new release pull request. See https://voxpupuli.org/docs/releasing_version/ or a previous release PR for info and examples.

**Comment by rwaffen** [comment]
oh, didn't know this. will do this tomorrow. thanks for the info. :)

**Comment by tsmgeek** [comment]
I am not sure the full list of changes for a changelog.
- gluster version changed 3.12 -> 7.3 (note they are now up at 7.9, and there is a 8.x branch too)
https://docs.gluster.org/en/latest/release-notes/7.9/
https://docs.gluster.org/en/latest/release-notes/8.3/

**Comment by tsmgeek** [comment]
Any movement on this, the module is so old on forge.

**Comment by tsmgeek** [comment]
Seems this is a dead module as there are no maintainers working on it.

**Comment by tsmgeek** [comment]
@rwaffen Can you update puppet forge with later version?

**Comment by rwaffen** [comment]
New v.6.0.0 was released just now
