### ISSUE TITLE
Broken facts on gluster3.2

### ISSUE THREAD

**Issue by bastelfreak** [voxpupuli/puppet-gluster#56]
Please check the following items before submitting an issue -- thank you!

Nnote that this project is released with a Contributor Code of Conduct.
By participating in this project you agree to abide by its terms.
[Contributor Code of Conduct](https://voxpupuli.org/coc/).
- [x] There is no existing issue or PR that addresses this problem

Optional, but makes our lives much easier:
- [x] The issue affects the latest release of this module at the time of
  submission

---
### Affected Puppet, Ruby, OS and module versions/distributions

Puppet3.8.7, Ruby1.8.3, CentOS6
### What are you seeing

```
# facter -p
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `/usr/sbin/gluster volume info (position'
sh: -c: line 0: syntax error near unexpected token `)'
sh: -c: line 0: `/usr/sbin/gluster volume info 1)'
```
### What behaviour did you expect instead

seeing cluster facts
### How did this behaviour get triggered

fact expected nonexistent output to parse
### Any additional information you'd like to impart

the fact does `gluster volume list`. This command isn't available on old gluster versions (3.2 in my case). The output is:

```
# gluster volume list
unrecognized word: list (position 1)
```

**Comment by DarkGigaByte** [comment]
`gluster volume info all` is available in gluster version 3.2

**Comment by sammcj** [comment]
I would suggest upgrading gluster to a modern version as 3.2 is _very_ old!

**Comment by ekohl** [comment]
Agreed. Closing due to its age.
