### ISSUE TITLE
Tries to create duplicate volumes if there's only one gluster node

### ISSUE THREAD

**Issue by tmannerm** [voxpupuli/puppet-gluster#6]
Currently this module tries to create volumes again, which is obviously fails because they already exist. This happens when there are no peers (so only one node in the pool) because in that case no volume facts are created and thus they are not seen by the creating code.

This seems to stem from the two checks at Gluster fact provider [line 28](https://github.com/covermymeds/puppet-gluster/blob/master/lib/facter/gluster.rb#L28) and [line 58](https://github.com/covermymeds/puppet-gluster/blob/master/lib/facter/gluster.rb#L58).

I'm not sure what's the best fix this situation. Maybe the volume facts should be provided in this case too but in that case the peer count check is not needed.

**Comment by jyaworski** [comment]
Is this still an issue?

**Comment by skpy** [comment]
It's a valid question as to whether this module should support a one-node Gluster configuration; or if this module will only support multi-node Gluster configurations.  I don't have a need for a single-server Gluster volume, but that doesn't mean that no one will.
