### ISSUE TITLE
Can't add yum repositories

### ISSUE THREAD

**Issue by mkmet** [voxpupuli/puppet-gluster#68]
### Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 3.8.7
- Ruby: 2.0.0p598
- Distribution: CentOS 7.2.1511
- Module version: 2.2.0

Can't add yum repositories in CentOS with repo class due to new repositories location for GlusterFS 3.8 and later. More at https://download.gluster.org/pub/gluster/glusterfs/3.8/LATEST/EPEL.repo/.

**Comment by bastelfreak** [comment]
Hi @mkmet, we recently merged https://github.com/voxpupuli/puppet-gluster/pull/69, can you please test if this fixes your issues?

**Comment by mkmet** [comment]
Hi @bastelfreak. Still no success:
```
Error: /Stage[main]/Gluster::Install/Package[glusterfs-fuse]/ensure: change from absent to present failed: Execution of '/bin/yum -d 0 -e 0 -y install glusterfs-fuse' returned 1: warning: /var/cache/yum/x86_64/7/glusterfs-x86_64/packages/glusterfs-3.8.4-1.el7.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID e451e5b5: NOKEY


The GPG keys listed for the "CentOS-7 - Gluster 3.8" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.


 Failing package is: glusterfs-3.8.4-1.el7.x86_64
 GPG Keys are configured as: http://mirror.centos.org/centos/RPM-GPG-KEY-CentOS-7
```
It looks like currently GPG key for standard CentOS repo is downloaded. However CentOS storage SIG uses separate key for they packages.

**Comment by tux-o-matic** [comment]
The CentOS SIG in charge of distributing GlusterFS packages for EL sign those packages with a separate key which is installed by 'centos-release-storage-common', a package from the CentOS Extras.

So in other words, that CentOS choice leads to problems for RHEL or Scientific Linux where you'd need to manually install CentOS rpm to skip the Extras repo.

@bastelfreak, if you agree, I'll do a PR to change the URL source of the GPG key from [general one](http://mirror.centos.org/centos/RPM-GPG-KEY-CentOS-7) to the Storage SIG one which is sadly only available (outside an rpm) on [GitHub](https://raw.githubusercontent.com/CentOS-Storage-SIG/centos-release-storage-common/master/RPM-GPG-KEY-CentOS-SIG-Storage).

**Comment by mkmet** [comment]
I already prepared changes with key from [GitHub](https://raw.githubusercontent.com/CentOS-Storage-SIG/centos-release-storage-common/master/RPM-GPG-KEY-CentOS-SIG-Storage) and created PR #74  yesterday. I only forgot to reference issue ...sorry :-).
