### ISSUE TITLE
Heketi Support

### ISSUE THREAD

**Issue by sammcj** [voxpupuli/puppet-gluster#81]
Hello,

It would be fantastic if Heketi support could be added to install and manage the Heketi package / service and basic config (authentication etc...) for whatever service is going to interact with it (i.e. kubes etc...)

Thoughts?

**Comment by tux-o-matic** [comment]
Sounds like a lot of overlapping between volumes defined in Puppet and volumes managed via the Heketi API.

**Comment by sammcj** [comment]
Yeah, there's still _a_ need to install gluster and heketi packages and configure their basic configs, but after spending a few days testing it - we're not going to use it as it actually adds a SPOF to Gluster by depending on a single database on a single node thats stateful! (seems like madness to me).

So, I'm going to close this for now, but if the SPOF is removed it might still prove useful, as it does provide quick and clean autoprovisioning for services such as Kubenetes etc...
